services:
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./back-end
    ports:
      - "5000:5000"
    volumes:
      - ./back-end:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/blogdb
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
